// Mock Lesson Plans (JSX-friendly, no TypeScript)

export const MOCK_LESSON_PLANS = [
  {
    id: "1",
    title: "Introduction to Data Structures",
    subject: "Computer Science",
    grade: "10th Grade",
    date: "2024-08-21",
    duration: 90,
    objectives: [
      "Understand basic data structure concepts",
      "Learn about arrays and linked lists",
      "Implement simple data structures",
    ],
    materials: [
      "Whiteboard and markers",
      "Laptop with IDE",
      "Data structure reference book",
      "Practice worksheets",
    ],
    activities: [
      {
        id: "1",
        name: "Introduction",
        description: "Brief overview of data structures and their importance",
        duration: 15,
        type: "lecture",
      },
      {
        id: "2",
        name: "Arrays Explanation",
        description: "Detailed explanation of arrays with examples",
        duration: 25,
        type: "lecture",
      },
      {
        id: "3",
        name: "Hands-on Practice",
        description: "Students implement basic array operations",
        duration: 30,
        type: "practical",
      },
      {
        id: "4",
        name: "Q&A Session",
        description: "Address student questions and clarify concepts",
        duration: 15,
        type: "discussion",
      },
      {
        id: "5",
        name: "Wrap-up",
        description: "Summary and preview of next lesson",
        duration: 5,
        type: "lecture",
      },
    ],
    assessment: "Quick quiz on array concepts and operations",
    homework: "Complete practice problems 1-5 from textbook",
    notes:
      "Students showed good understanding of basic concepts. Need more time for practical exercises.",
    status: "completed",
    createdAt: "2024-08-15",
    updatedAt: "2024-08-21",
  },
  {
    id: "2",
    title: "Object-Oriented Programming Basics",
    subject: "Computer Science",
    grade: "10th Grade",
    date: "2024-08-23",
    duration: 90,
    objectives: [
      "Understand OOP principles",
      "Learn about classes and objects",
      "Practice creating simple classes",
    ],
    materials: [
      "Programming environment",
      "OOP reference materials",
      "Code examples",
      "Practice exercises",
    ],
    activities: [
      {
        id: "1",
        name: "OOP Concepts",
        description: "Introduction to encapsulation, inheritance, polymorphism",
        duration: 20,
        type: "lecture",
      },
      {
        id: "2",
        name: "Class Creation",
        description: "Demonstrate creating classes and objects",
        duration: 25,
        type: "practical",
      },
      {
        id: "3",
        name: "Student Practice",
        description: "Students create their own simple class",
        duration: 35,
        type: "practical",
      },
      {
        id: "4",
        name: "Review",
        description: "Review key concepts and common mistakes",
        duration: 10,
        type: "discussion",
      },
    ],
    assessment: "Code review of student-created classes",
    homework: "Create a Person class with properties and methods",
    notes: "",
    status: "approved",
    createdAt: "2024-08-16",
    updatedAt: "2024-08-20",
  },
  {
    id: "3",
    title: "Advanced Algorithms",
    subject: "Computer Science",
    grade: "10th Grade",
    date: "2024-08-25",
    duration: 90,
    objectives: [
      "Understand sorting algorithms",
      "Implement bubble sort and quick sort",
      "Analyze algorithm complexity",
    ],
    materials: [
      "Algorithm visualization tools",
      "Coding environment",
      "Complexity analysis charts",
    ],
    activities: [
      {
        id: "1",
        name: "Algorithm Introduction",
        description: "Overview of sorting algorithms and their applications",
        duration: 20,
        type: "lecture",
      },
      {
        id: "2",
        name: "Bubble Sort Demo",
        description: "Step-by-step implementation of bubble sort",
        duration: 25,
        type: "practical",
      },
      {
        id: "3",
        name: "Quick Sort Implementation",
        description: "Students implement quick sort algorithm",
        duration: 30,
        type: "practical",
      },
      {
        id: "4",
        name: "Complexity Analysis",
        description: "Discuss time and space complexity",
        duration: 15,
        type: "discussion",
      },
    ],
    assessment: "Algorithm implementation and complexity analysis",
    homework: "Research and implement merge sort algorithm",
    notes: "",
    status: "draft",
    createdAt: "2024-08-18",
    updatedAt: "2024-08-18",
  },
]
